services:
  project-zomboid-dedicated-server:
    container_name: project-zomboid-dedicated-server
    image: project-zomboid-dedicated-server:latest
    build:
      network: host
      context: build
    environment:
      - server_name=servertest
      - update_server_files=false
    volumes:
      - ./server-files:/home/steam/server-files
      - ./server-data:/home/steam/Zomboid
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
    stdin_open: true
    tty: true